version: '3.7'
services: 
   
    eureka-server:
        image: ram1uj/eureka-server:0.1
        ports: 
            - "8761:8761"
        restart: always
       
        networks:
            - app-network
    
    coupon-service:
        image: ram1uj/product-service:0.1
        ports: 
            - "5100:5100"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
                
        depends-on:
            - eureka-server
        networks:
            - app-network
 
    coupon-service:
        image: ram1uj/coupon-service:0.1
        ports: 
            - "5200:5200"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
        
        depends-on:
            - eureka-server
        networks:
            - app-network

    order-service:
        image: ram1uj/order-service:0.1
        ports: 
            - "5000:5000"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
        depends-on:
            - eureka-server
        networks:
            - app-network
 
# Networks to be created to facilitate communication between containers
networks:
    app-network:  