version: '3.7'
services: 
    
    product-service:
        image: ram1uj/product-service:1.0
        ports: 
            - "5100-5199:5100"
        restart: always
        environment:
            - spring.profiles.active : ecs
        networks:
            - app-network
 
    coupon-service:
        image: ram1uj/coupon-service:1.0
        ports: 
            - "5200-5299:5200"
        restart: always
        environment:
            - spring.profiles.active : ecs

        networks:
            - app-network

    order-service:
        image: ram1uj/order-service:1.0
        ports: 
            - "5000-5099:5000"
        restart: always
        environment:
            - spring.profiles.active : ecs
            - COUPON-SERVICE-URI : coupon-service:5200
            - PRODUCT-SERVICE-URI : product-service:5100
        networks:
            - app-network
 
# Networks to be created to facilitate communication between containers
networks:
    app-network:  